<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMasterPage.Master" AutoEventWireup="true" CodeBehind="AddCategory.aspx.cs" Inherits="crocusProject.AddCategory"  MaintainScrollPositionOnPostBack="true" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

    <style>
        body {
            margin: 0;
            font-family: Segoe UI;
            background: #f5f5f5;
        }


        /* Form Box */
        .container {
            width: 400px;
            margin: 120px auto; /* center ma lavse */
            padding: 30px;
            /*    background: white;*/
            /*    border-radius: 10px;
    box-shadow: 0px 0px 10px gray;*/
        }

        /* Heading */
        h2 {
            text-align: center;
        }

        /* Input size moto */
        input[type=text], textarea {
            width: 100%;
            padding: 8px;
            margin-top: 5px;
        }

        /* Button style */
        button, input[type=submit] {
            width: 100%;
            padding: 10px;
            background: #4f6f3c;
            color: white;
            border: none;
            margin-top: 10px;
            font-size: 16px;
            cursor: pointer;
        }

        .tb {
            border: 1px solid black;
            border-collapse: collapse;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

     <div class="header">
     <h2>Add Category</h2>
 </div>

    <div class="container">
        <table>

            <tr>
                <td>Category Name :</td>
                <td>
                    <asp:TextBox ID="txtCategoryName" runat="server"></asp:TextBox>
                </td>
            </tr>





            <tr>
                <td></td>
                <td>
                    <asp:Button ID="btnSave" runat="server" Text="Save Category" OnClick="btnSave_Click" />
                </td>
            </tr>

        </table>
    </div>


        <div class="header">
    <h2>All Category</h2>
</div>    <br /><br /><br />
    <!--<div>
        <asp:Repeater ID="rptcat" runat="server">
            <HeaderTemplate>
                <table style="width: 50%; margin: auto; text-align: center;" class="tb">
                    <thead>
                        <tr class="tb">
                            <th class="tb">Category Id</th>
                            <th class="tb">Category Name</th>
                        </tr>
                    </thead>
                    <tbody>
            </HeaderTemplate>

            <ItemTemplate>
                <tr class="tb">
                    <td class="tb"><%# Eval("CategoryId") %></td>
                    <td class="tb"><%# Eval("CategoryName") %></td>
                </tr>
            </ItemTemplate>
            <FooterTemplate>
                </tbody>

                </table>
            </FooterTemplate>
        </asp:Repeater>
    </div>-->
    <center>
    <asp:GridView ID="gv_cate" runat="server" Width="100%" style="text-align:center;"
        AutoGenerateDeleteButton="True" 
        DataKeyNames="CategoryId"
        OnRowDeleting="gv_cate_RowDeleting"
        OnRowEditing="gv_cate_RowEditing" 
        AutoGenerateEditButton="True" 
        OnRowCancelingEdit="gv_cate_RowCancelingEdit" OnRowUpdating="gv_cate_RowUpdating" OnRowDataBound="gv_cate_RowDataBound" ShowFooter="True">

    </asp:GridView>


        </center>
    <br /><br />
</asp:Content>
