<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMasterPage.Master" AutoEventWireup="true" CodeBehind="AddProducts.aspx.cs" Inherits="crocusProject.Adminpage" MaintainScrollPositionOnPostBack="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
<style>
body { margin:0; font-family:Segoe UI; background:#f5f5f5; }
.container { width: 400px; margin: 100px auto; padding: 30px; }
.header { background:white; padding:10px; box-shadow:0 2px 5px rgba(0,0,0,0.1); }
h2{ text-align:center; }
input[type=text], textarea{ width:100%; padding:8px; margin-top:5px; }
button, input[type=submit]{ width:100%; padding:10px; background:#4f6f3c; color:white; border:none; margin-top:10px; font-size:16px; cursor:pointer; }
.tb { border:1px solid black; border-collapse:collapse; }
.con { margin:90px auto; padding:20px; }
</style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<!-- Add Product Form -->
<div class="header"><h2>Add Product</h2></div>
<div class="container">
    <table>
        <tr>
            <td>Category :</td>
            <td>
                <asp:DropDownList ID="ddcat" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddcat_SelectedIndexChanged"></asp:DropDownList>
            </td>
        </tr>
        <tr>
            <td>SubCategory :</td>
            <td>
                <asp:DropDownList ID="ddsubcat" runat="server"></asp:DropDownList>
            </td>
        </tr>
        <tr>
            <td>Product Name :</td>
            <td><asp:TextBox ID="txtProductName" runat="server"></asp:TextBox></td>
        </tr>
        <tr>
            <td>Price :</td>
            <td><asp:TextBox ID="txtPrice" runat="server"></asp:TextBox></td>
        </tr>
        <tr>
            <td>Selling Price :</td>
            <td><asp:TextBox ID="txtsellprice" runat="server"></asp:TextBox></td>
        </tr>
        <tr>
            <td>Description :</td>
            <td><asp:TextBox ID="txtDescription" runat="server" TextMode="MultiLine"></asp:TextBox></td>
        </tr>
        <tr>
            <td>Product Image :</td>
            <td><asp:FileUpload ID="FileUpload1" runat="server" /></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <asp:Button ID="btnSave" runat="server" Text="Save Product" OnClick="btnSave_Click" />
            </td>
        </tr>
    </table>
</div>

<!-- All Products Grid -->

<div class="header"><h2>All Products</h2></div>
    <br /><br /><br />
    <center>
<asp:GridView ID="gv_product" runat="server" AutoGenerateColumns="False" DataKeyNames="ProductId" Width="100%" style="text-align:center;"
    AutoGenerateEditButton="True" AutoGenerateDeleteButton="True"
    OnRowEditing="gv_product_RowEditing" OnRowUpdating="gv_product_RowUpdating"
    OnRowCancelingEdit="gv_product_RowCancelingEdit" OnRowDeleting="gv_product_RowDeleting"
    OnRowDataBound="gv_product_RowDataBound">

    <Columns>
        <asp:BoundField DataField="ProductId" HeaderText="ID" ReadOnly="true" />

        <asp:TemplateField HeaderText="Category">
            <ItemTemplate>
                <%# Eval("CategoryName") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:DropDownList ID="ddcatEdit" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddcatEdit_SelectedIndexChanged"></asp:DropDownList>
            </EditItemTemplate>
        </asp:TemplateField>

        <asp:TemplateField HeaderText="SubCategory">
            <ItemTemplate>
                <%# Eval("subCategoryName") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:DropDownList ID="ddsubcatEdit" runat="server"></asp:DropDownList>
            </EditItemTemplate>
        </asp:TemplateField>


   <asp:TemplateField HeaderText="Product Name">
            <ItemTemplate>
                <%# Eval("ProductName") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtProductName" runat="server" Text='<%# Bind("ProductName") %>'></asp:TextBox>
            </EditItemTemplate>
        </asp:TemplateField>
        


 <asp:TemplateField HeaderText="Price">
            <ItemTemplate>
                <%# Eval("Price") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtPrice" runat="server" Text='<%# Bind("Price") %>'></asp:TextBox>
            </EditItemTemplate>
        </asp:TemplateField>

        
           <asp:TemplateField HeaderText="Selling Price">
            <ItemTemplate>
                <%# Eval("SellingPrice") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtsellprice" runat="server" Text='<%# Bind("SellingPrice") %>'></asp:TextBox>
            </EditItemTemplate>
        </asp:TemplateField>


        <asp:TemplateField HeaderText="Description">
            <ItemTemplate>
                <%# Eval("Description") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtDescription" runat="server" Text='<%# Bind("Description") %>' TextMode="MultiLine"></asp:TextBox>
            </EditItemTemplate>
        </asp:TemplateField>

        <asp:BoundField DataField="Image" HeaderText="Image" />


                <asp:TemplateField HeaderText="Product Name">
    <ItemTemplate>
       
            <div style="display:flex; justify-content:center; align-items:center;">
 <img src='<%# ResolveUrl(Eval("Image").ToString()) %>' 
     style="width:100px;height:100px;border-radius:8px;" />
        </div>
    </ItemTemplate>
</asp:TemplateField>



    </Columns>
</asp:GridView>
        </center>
</asp:Content>